/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _CLOCK_CONFIG_H_
#define _CLOCK_CONFIG_H_

#include "fsl_common.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes default configuration of clocks.
 *
 */
void BOARD_InitBootClocks(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ********************* Configuration BOARD_Boot_Clock_RUN **********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_Boot_Clock_RUN configuration
 ******************************************************************************/
#define BOARD_BOOT_CLOCK_RUN_CORE_CLOCK           120000000U  /*!< Core clock frequency: 120000000Hz */

/*! @brief MCG set for BOARD_Boot_Clock_RUN configuration.
 */
extern const mcg_config_t mcgConfig_BOARD_Boot_Clock_RUN;
/*! @brief SIM module set for BOARD_Boot_Clock_RUN configuration.
 */
extern const sim_clock_config_t simConfig_BOARD_Boot_Clock_RUN;
/*! @brief OSC set for BOARD_Boot_Clock_RUN configuration.
 */
extern const osc_config_t oscConfig_BOARD_Boot_Clock_RUN;

/*******************************************************************************
 * API for BOARD_Boot_Clock_RUN configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_Boot_Clock_RUN(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

#endif /* _CLOCK_CONFIG_H_ */

